apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: blog
build:
  artifacts:
    - image: emre/client
      context: client
      docker:
        dockerfile: Dockerfile
    - image: emre/comments
      context: comments
      docker:
        dockerfile: Dockerfile
    - image: emre/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
    - image: emre/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
    - image: emre/posts
      context: posts
      docker:
        dockerfile: Dockerfile
    - image: emre/query
      context: query
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/client-depl.yaml
    - infra/k8s/comments-depl.yaml
    - infra/k8s/event-bus-depl.yaml
    - infra/k8s/ingress-srv.yaml
    - infra/k8s/moderation-depl.yaml
    - infra/k8s/post-depl.yaml
    - infra/k8s/posts-srv.yaml
    - infra/k8s/query.depl.yaml
