apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: ticketing-dev
build:
  local:
    push: false
  artifacts:
    - image: ticketing-dev/auth
      context: auth
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/auth-depl.yaml
    - infra/k8s/ingress-srv.yaml
